/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DModules.DMTrabajadores;
import DSources.DSTrabajadores;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eromero
 */
public class FAutenticar extends javax.swing.JFrame {

    /**
     * Creates new form FAutenticar
     */
    public static DSTrabajadores usuario;
    public DMTrabajadores qry;
    public String descripcion;
    public String contraseña;
    public static boolean autentificar;
    public List<DSTrabajadores> ListTrabajadores= new ArrayList();
     
    

    public FAutenticar() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBTrabajadores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        BEntrarAutenticacion = new javax.swing.JButton();
        BCancelarAutenticacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        jLabel1.setText("AUTENTICACIÓN DE USUARIOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jPasswordField1.setDragEnabled(true);
        jPasswordField1.setFocusCycleRoot(true);

        BEntrarAutenticacion.setLabel("Entrar");
        BEntrarAutenticacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrarAutenticacionActionPerformed(evt);
            }
        });

        BCancelarAutenticacion.setText("Cancelar");
        BCancelarAutenticacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarAutenticacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(BEntrarAutenticacion)
                        .addGap(54, 54, 54)
                        .addComponent(BCancelarAutenticacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEntrarAutenticacion)
                    .addComponent(BCancelarAutenticacion))
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEntrarAutenticacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrarAutenticacionActionPerformed
        // TODO add your handling code here:
        contraseña = new String(jPasswordField1.getPassword());
        String nombreSeleccionado = (String) CBTrabajadores.getSelectedItem();

        
        System.out.println("Intentando entrar con: " + nombreSeleccionado);
        System.out.println("Total trabajadores en lista: " + ListTrabajadores.size());

        boolean encontrado = false;

        for (DSTrabajadores t : ListTrabajadores) {
            // Comparamos la descripción para identificar al trabajador
            // y el NIF para la contraseña 
            if (t.getDescripcion().equals(nombreSeleccionado)) {
                System.out.println("Usuario localizado. Validando contraseña...");

                if (t.getNif().equals(contraseña)) { 
                    usuario = t;
                    autentificar = true;
                    encontrado = true;
                    System.out.println("Autenticación exitosa para: " + t.getNombre());
                    break; // Salimos del bucle si ya lo encontramos
                } else {
                    System.out.println("Contraseña incorrecta para el usuario.");
                }
            }
        }

        if (encontrado) {
            this.dispose();                
            new FMenPrincipal().setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", 
                    "Error de acceso", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
 
    }//GEN-LAST:event_BEntrarAutenticacionActionPerformed

    private void BCancelarAutenticacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarAutenticacionActionPerformed
        // TODO add your handling code here:
        dispose();
        new FMenPrincipal().setVisible(true);
    }//GEN-LAST:event_BCancelarAutenticacionActionPerformed

   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        
        cargarTrabajadores();
    }//GEN-LAST:event_formWindowOpened

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new FAutenticar().setVisible(true);
        
               
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelarAutenticacion;
    private javax.swing.JButton BEntrarAutenticacion;
    private javax.swing.JComboBox<String> CBTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

    private void cargarTrabajadores(){
          qry = new DMTrabajadores();
        
        try {
            ListTrabajadores = qry.QryCargaTrabajadores();
                    } catch (SQLException ex) {
            Logger.getLogger(FAutenticar.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Se ha cargado el Array List de Trabajadores");
        for (DSTrabajadores Cursor : ListTrabajadores)
           {
               this.descripcion = Cursor.getDescripcion();
               this.CBTrabajadores.addItem(descripcion);
            }

    }

}
