/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;



import DSources.DSObras;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


public class FMantenimO extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FMantenimO.class.getName());
    public  List<DSObras> InfoObras= new ArrayList();
    public DModules.DMObras Objqry = new DModules.DMObras();

    /**
     * Creates new form FMantenimO
     */
    public FMantenimO() {
        initComponents();
        Aliniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextCodigo = new javax.swing.JTextField();
        TextFechaTer = new javax.swing.JTextField();
        TextDescripcion = new javax.swing.JTextField();
        botonInsertar = new javax.swing.JButton();
        Descuento1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboxCodigo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        FechaText2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DescripText2 = new javax.swing.JTextField();
        BotonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        Descuento2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU MANTENIMIENTO OBRAS");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Fecha Termina:");

        jLabel4.setText("Descuento:");

        jLabel5.setText("Descripcion:");

        TextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodigoActionPerformed(evt);
            }
        });

        TextFechaTer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFechaTerActionPerformed(evt);
            }
        });

        TextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDescripcionActionPerformed(evt);
            }
        });

        botonInsertar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonInsertar.setText("Guardar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFechaTer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Descuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(botonInsertar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(botonInsertar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextFechaTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Descuento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insertar", jPanel1);

        jLabel6.setText("Codigo:");

        comboxCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxCodigoItemStateChanged(evt);
            }
        });
        comboxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCodigoActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha:");

        FechaText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaText2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Descuento:");

        jLabel9.setText("Descripcion:");

        DescripText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripText2ActionPerformed(evt);
            }
        });

        BotonModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descuento2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(FechaText2)
                    .addComponent(DescripText2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Descuento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescripText2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar)
                        .addGap(37, 37, 37))))
        );

        jTabbedPane1.addTab("Modificar-Eliminar", jPanel2);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        // TODO add your handling code here:
        
        String Codigo = TextCodigo.getText().trim();
        String FechaTer = TextFechaTer.getText().trim();
        int Descuento = (int)Descuento1.getValue();
        String Descripcion = TextDescripcion.getText().trim();
 

    // Validar datos mínimos
    if (Codigo.isEmpty() || FechaTer.isEmpty() || Descripcion.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debes completar todos los campos.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

   

    // Llamar al método de inserción
    boolean exito = Objqry.insertarObra(Codigo, FechaTer, Descuento,Descripcion);

    // Mostrar resultado
    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Insertado correctamente.", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar campos
        
        TextFechaTer.setText("");
        TextCodigo.setText("");
        TextDescripcion.setText("");
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "No se pudo guardar la obra .", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void TextFechaTerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFechaTerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFechaTerActionPerformed

    private void TextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodigoActionPerformed

    private void TextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDescripcionActionPerformed

    private void FechaText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaText2ActionPerformed

    private void comboxCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxCodigoItemStateChanged
        // TODO add your handling code here:
         try {
            InfoObras = Objqry.QryCargaTodaInfoObras();
                    } catch (SQLException ex) {
            Logger.getLogger(FAutenticar.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Tamaño lista: " + InfoObras.size());
            for (DSObras t : InfoObras) {
            System.out.println(" -> " + t.getCodigo());
        }
        
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String codigo_obra = (String) comboxCodigo.getSelectedItem();
        if (codigo_obra == null ) return;

        for (DSObras obra : InfoObras) {
            if (obra.getCodigo().equals(codigo_obra)) {
                // Cargar los datos en los campos
                DescripText2.setText(obra.getDescripcion());
                FechaText2.setText(obra.getFecha_Termina());
                Descuento2.setValue(obra.getDescuento());

                break;
            }
        }
    }
    }//GEN-LAST:event_comboxCodigoItemStateChanged

    public void Aliniciar(){ 
        try {
            InfoObras = Objqry.QryCargaTodaInfoObras();
                    } catch (SQLException ex) {
            Logger.getLogger(FAutenticar.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Se ha cargado el Array List de Trabajadores");
        for (DSObras Cursor : InfoObras)
           {
               String codigo = Cursor.getCodigo();
               comboxCodigo.addItem(codigo);
            }
    }
    
    
    private void DescripText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripText2ActionPerformed

    private void comboxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        FMenPrincipal fm = new FMenPrincipal();
        fm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // TODO add your handling code here:
        int descuento= (int)Descuento2.getValue();
        String codigo_obra = (String) comboxCodigo.getSelectedItem();
        String fecha= FechaText2.getText();
        String descripcion = DescripText2.getText().trim();
      

   

    // Validar datos mínimos
    if (codigo_obra.isEmpty() || fecha.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debes completar todos los campos.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }


    // Llamar al método de inserción
    boolean exito = Objqry.modificarObra(codigo_obra,fecha, descuento,descripcion);

    // Mostrar resultado
    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, "Modificado correctamente.", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar campos
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "No se pudo modificar la obra.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
       
        //validar codigo no tenga servicios 
        String codigo_obra = (String) comboxCodigo.getSelectedItem();
        
                
       boolean codigoTieneServicios = Objqry.codigoEnServicio(codigo_obra);
    
        if (codigoTieneServicios) {
             javax.swing.JOptionPane.showMessageDialog(this, 
                "No se puede eliminar la obra porque tiene servicios asociados.", 
                "Error de Eliminación", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detener el proceso si tiene servicios
        }
    
    
    // Validar datos mínimos
    if (codigo_obra.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debes completar el codigo de obra.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear instancia del módulo de consultas
    ;

    // Llamar al método de inserción
    boolean exito = Objqry.eliminarObra(codigo_obra);

    // Mostrar resultado
    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, "Eliminado correctamente.", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar campos
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "No se pudo eleminar la obra.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FMantenimO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModificar;
    private javax.swing.JTextField DescripText2;
    private javax.swing.JSpinner Descuento1;
    private javax.swing.JSpinner Descuento2;
    private javax.swing.JTextField FechaText2;
    private javax.swing.JTextField TextCodigo;
    private javax.swing.JTextField TextDescripcion;
    private javax.swing.JTextField TextFechaTer;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JComboBox<String> comboxCodigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
