/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
                             
package Formularios;

import DSources.*;
import DBConexiones.ConexionDB;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author eromero
 */
public class FMenPrincipal extends javax.swing.JFrame {
    
    
    boolean comprueba= FAutenticar.autentificar;
    DSTrabajadores user= FAutenticar.usuario;
    int Tipo;
    
    /**
     * Creates new form FMenPrincipal
     */
    
    public FMenPrincipal() {
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JLUsuario = new javax.swing.JLabel();
        JTEUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuOperac = new javax.swing.JMenu();
        jMMantenimiento = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenServicios = new javax.swing.JMenuItem();
        jMenuAutenti = new javax.swing.JMenu();
        jMenLogin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuCerrar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuAyuda = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLUsuario.setForeground(new java.awt.Color(0, 153, 51));
        JLUsuario.setToolTipText("");
        JLUsuario.setEnabled(false);
        JLUsuario.setFocusable(false);

        JTEUsuario.setEditable(false);
        JTEUsuario.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        JTEUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTEUsuario.setEnabled(false);
        JTEUsuario.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Gestión de los Trabajos");

        jMenuOperac.setText("Operaciones");

        jMMantenimiento.setText("Mantenimiento");
        jMMantenimiento.setEnabled(false);
        jMMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMantenimientoActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Obras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMMantenimiento.add(jMenuItem2);

        jMenuItem1.setText("Trabajadores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMMantenimiento.add(jMenuItem1);

        jMenuOperac.add(jMMantenimiento);
        jMenuOperac.add(jSeparator2);

        jMenServicios.setText("Servicios");
        jMenServicios.setEnabled(false);
        jMenServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenServiciosActionPerformed(evt);
            }
        });
        jMenuOperac.add(jMenServicios);

        jMenuBar2.add(jMenuOperac);

        jMenuAutenti.setText("Autenticar");

        jMenLogin.setText("Login");
        jMenLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenLoginActionPerformed(evt);
            }
        });
        jMenuAutenti.add(jMenLogin);
        jMenuAutenti.add(jSeparator1);

        jMenuCerrar.setText("Cerrar Cesion");
        jMenuCerrar.setEnabled(false);
        jMenuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarActionPerformed(evt);
            }
        });
        jMenuAutenti.add(jMenuCerrar);

        jMenuBar2.add(jMenuAutenti);

        jMenu5.setText("Informes");

        jMenuItem3.setText("Listado Trabajadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem7.setText("Listado Obras");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem5.setText("Ingresos Trabajador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem8.setText("Ingresos Obras");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Graficos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem6.setText("Parametros");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar2.add(jMenu5);

        jMenu4.setText("Ayuda");

        jMenuAyuda.setText("Ayuda en linea");
        jMenu4.add(jMenuAyuda);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JTEUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(JLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTEUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FAutenticar().setVisible(true);
    }//GEN-LAST:event_jMenLoginActionPerformed

    
    private void jMenServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenServiciosActionPerformed
        // TODO add your handling code here:
        dispose();
        FormServicios fs = new FormServicios();
        fs.setVisible(true);
    }//GEN-LAST:event_jMenServiciosActionPerformed

    private void jMenuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarActionPerformed
        // TODO add your handling code here:
         // Limpia los valores globales de autenticación
     
        FAutenticar.usuario = null;
        FAutenticar.autentificar = false;

        // Cierra la ventana actual
        this.dispose();

        // Crea una nueva ventana principal limpia
        FMenPrincipal fm = new FMenPrincipal();
        fm.setVisible(true);
    }//GEN-LAST:event_jMenuCerrarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FObras fo= new FObras();
        fo.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMMantenimientoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FTrabajadores fm= new FTrabajadores();
        fm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
       try{
               ConexionDB ConInfObras = new ConexionDB();
               Connection conInfObras;
               conInfObras = ConInfObras.conex;
               String RutaRelativa = "./Informes/ListadoTrabajadores.jasper";
               JasperReport inforObras;
               try{
                   inforObras = (JasperReport) JRLoader.loadObjectFromFile(RutaRelativa);
                   JasperPrint PrintInfoObras;
                   PrintInfoObras = JasperFillManager.fillReport(inforObras, null, conInfObras);
                   JasperViewer JpViewerInfObras = new JasperViewer(PrintInfoObras, false);
                   JpViewerInfObras.setVisible(true);
               } catch (JRException ex){
            
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al cargar o rellenar el informe de JasperReports.", ex);
        }

    } catch (SQLException ex) { 
        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al establecer la conexión con la base de datos.", ex);
    }
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
         try{
               ConexionDB ConInfObras = new ConexionDB();
               Connection conInfObras;
               conInfObras = ConInfObras.conex;
               String RutaRelativa = "./Informes/ListadoObras.jasper";
               JasperReport inforObras;
               try{
                   inforObras = (JasperReport) JRLoader.loadObjectFromFile(RutaRelativa);
                   JasperPrint PrintInfoObras;
                   PrintInfoObras = JasperFillManager.fillReport(inforObras, null, conInfObras);
                   JasperViewer JpViewerInfObras = new JasperViewer(PrintInfoObras, false);
                   JpViewerInfObras.setVisible(true);
               } catch (JRException ex){
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al cargar o rellenar el informe de JasperReports.", ex);
        }

    } catch (SQLException ex) {
        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al establecer la conexión con la base de datos.", ex);
    }
       
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try{
               ConexionDB ConInfObras = new ConexionDB();
               Connection conInfObras;
               conInfObras = ConInfObras.conex;
               String RutaRelativa = "./Informes/Horas_Trabajadores.jasper";
               JasperReport inforObras;
               try{
                   inforObras = (JasperReport) JRLoader.loadObjectFromFile(RutaRelativa);
                   JasperPrint PrintInfoObras;
                   PrintInfoObras = JasperFillManager.fillReport(inforObras, null, conInfObras);
                   JasperViewer JpViewerInfObras = new JasperViewer(PrintInfoObras, false);
                   JpViewerInfObras.setVisible(true);
               } catch (JRException ex){
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al cargar o rellenar el informe de JasperReports.", ex);
        }

    } catch (SQLException ex) {
        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al establecer la conexión con la base de datos.", ex);
    }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FParametros p= new FParametros();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    
        try{
               ConexionDB ConInfObras = new ConexionDB();
               Connection conInfObras;
               conInfObras = ConInfObras.conex;
               String RutaRelativa = "./Informes/Horas_Obras.jasper";
               JasperReport inforObras;
               try{
                   inforObras = (JasperReport) JRLoader.loadObjectFromFile(RutaRelativa);
                   JasperPrint PrintInfoObras;
                   PrintInfoObras = JasperFillManager.fillReport(inforObras, null, conInfObras);
                   JasperViewer JpViewerInfObras = new JasperViewer(PrintInfoObras, false);
                   JpViewerInfObras.setVisible(true);
               } catch (JRException ex){
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al cargar o rellenar el informe de JasperReports.", ex);
        }

    } catch (SQLException ex) {
        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al establecer la conexión con la base de datos.", ex);
    }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try{
               ConexionDB ConInfObras = new ConexionDB();
               Connection conInfObras;
               conInfObras = ConInfObras.conex;
               String RutaRelativa = "./Informes/Grafico_Trabajadores.jasper";
               JasperReport inforObras;
               try{
                   inforObras = (JasperReport) JRLoader.loadObjectFromFile(RutaRelativa);
                   JasperPrint PrintInfoObras;
                   PrintInfoObras = JasperFillManager.fillReport(inforObras, null, conInfObras);
                   JasperViewer JpViewerInfObras = new JasperViewer(PrintInfoObras, false);
                   JpViewerInfObras.setVisible(true);
               } catch (JRException ex){
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al cargar o rellenar el informe de JasperReports.", ex);
        }

    } catch (SQLException ex) {
        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Error al establecer la conexión con la base de datos.", ex);
    }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        // 1. Localizar el archivo help_set.hs
        File fichero = new File("." + File.separator + "Ayuda" + File.separator + "help_set.hs");
        URL hsURL = null;
        try {
            hsURL = fichero.toURI().toURL();
        } catch (MalformedURLException ex) {
            System.getLogger(FMenPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        // 2. Crear el HelpSet y el HelpBroker
        HelpSet hs = null;
        try {
            hs = new HelpSet(getClass().getClassLoader(), hsURL);
        } catch (HelpSetException ex) {
            System.getLogger(FMenPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        HelpBroker hb = hs.createHelpBroker();

        // 3. Vincular al botón del menú y a la tecla F1
        // "Men_Principal" debe coincidir con un ID en tu map_file.jhm
        hb.enableHelpOnButton(jMenuAyuda, "intro", hs); 
        hb.enableHelpKey(getRootPane(), "intro", hs);
        
        
        
        this.setResizable(false); 
        this.setLocationRelativeTo(null); 
        
        if(this.user==null){
            jMenLogin.setEnabled(true);
             jMenuCerrar.setEnabled(false);
             jMMantenimiento.setEnabled(false);
             jMenServicios.setEnabled(false);
             
        }else if (comprueba){ 
            
            Tipo= user.getTipo();
            jMenLogin.setEnabled(false);
            jMenuCerrar.setEnabled(true);
            String name= user.getDescripcion();
            JLUsuario.setText(name);
            
           if(Tipo==1){
               jMMantenimiento.setEnabled(true);
               jMenServicios.setEnabled(false);
           
           }
           if(Tipo==0){
                jMMantenimiento.setEnabled(false);
                jMenServicios.setEnabled(true);
           }
 
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JTextField JTEUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMMantenimiento;
    private javax.swing.JMenuItem jMenLogin;
    private javax.swing.JMenuItem jMenServicios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuAutenti;
    private javax.swing.JMenuItem jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCerrar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuOperac;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
